# Generated by Django 5.0.6 on 2024-06-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='problems_id_291fda_idx')],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='blog_id_093a42_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='staff/')),
                ('work_time', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_info',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='staff_info_id_e4efcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_photo', models.ImageField(upload_to='user/')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('home_number', models.CharField(max_length=50)),
                ('user_number', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='user_info_id_6e1dc9_idx')],
            },
        ),
    ]
