# Generated by Django 5.0.6 on 2024-06-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffinfo',
            name='work_time',
            field=models.CharField(max_length=100),
        ),
    ]
