# Generated by Django 5.0.6 on 2024-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furni',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=34, verbose_name='nomi')),
                ('photo', models.CharField(blank=True, max_length=30, null=True, verbose_name='rasm ')),
                ('price', models.IntegerField(verbose_name='narxi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='tavsif')),
                ('category_code', models.IntegerField(verbose_name='category_code')),
                ('category_name', models.CharField(max_length=34, verbose_name='category_name')),
                ('subcategory_code', models.IntegerField(verbose_name='subcategory_code')),
                ('subcategory_name', models.CharField(max_length=34, verbose_name='subcategory_name')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True, verbose_name='full name')),
                ('user_name', models.CharField(max_length=200, null=True, unique=True, verbose_name='user name')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='telegram id')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
